# Default values for charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 6

fullnameOverride: "tron-live-parser"

envMaps:
  - configMapRef:
      name: tron-blocks-parser
      optional: false
  - configMapRef:
      name: kafka
      optional: false

env:

service:

ports:

preStop:
